/**
Proof of concept of injecting environment and command line arguments.

License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi.configurer.register.environment;

import aermicioi.aedi.configurer.register.register;
import aermicioi.aedi.storage.storage;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi.exception;

import std.process;

auto env(T)(Storage!(Object, string) storage, string variable, T default_) {
    import std.conv;
    string stringValueRepresentation = environment.get(variable);
    
    return storage.register(stringValueRepresentation !is null ? stringValueRepresentation.to!T : default_, variable);
}

auto env(T)(Storage!(Object, string) storage, string variable) {
    return storage.env!T(variable, T.init);
}

auto envs(T)(Storage!(Object, string) storage)
    if (is(T == struct)) {
    
    return storage.envs(T.init);
}
    
auto envs(T)(Storage!(Object, string) storage, T init)
    if (is(T == struct)) {
    
    foreach (member; publicFields!T) {
        import std.conv;
        import std.process;
        import std.array;
        
        string variable = environment.get(member.replace("__", "."));
        
        if (variable !is null) {
            storage.register(
                variable.to!(typeof(getMember!(T, member))),
                member.replace("__", ".")
            );
        } else {
            storage.register(
                __traits(getMember, init, member),
                member.replace("__", ".")
            );
        }
    }
    
    return storage;
}

auto args(T)(Storage!(Object, string) storage, string[] args, auto ref T container)
    if (is(T == struct)) {
    
    import std.getopt;
    import std.array;
            
    string generate(T)() {
        import std.algorithm;
        
        string statement;
        
        string[] members = [ publicFields!T ];
        sort(members);
        
        string[] getWithCommonPrefix(string[] args) {
            if (args.length > 0) {
                string[] res;
                res ~= args[0];
                
                foreach (arg; args[1 .. $]) {
                    if (commonPrefix(res[$ - 1], arg).length > 0) {
                        res ~= arg;
                    }
                }
                
                return res;
            }
            
            return null;
        }
        while (!members.empty) {
            string[] common = getWithCommonPrefix(members);
            if (common.length == 1) {
                statement ~= "\"" ~ common[0][0] ~ "|" ~ common[0].replace("__", ".") ~ "\", &container." ~ common[0] ~ ",";
            } else {
            
                foreach (element; common)  {
                    statement ~= '"' ~ element.replace("__", ".") ~ "\", &container." ~ element ~ ",";
                }
            }
            
            members = members[common.length .. $];
        }
        
        return statement;
    }
    mixin ("auto options = getopt(args, config.passThrough," ~ generate!T ~ ");");
    
    foreach (member; publicFields!T) {
        storage.register(
            __traits(getMember, container, member),
            member.replace("__", ".")
        );
    }
    
    return storage;
}
    
auto args(T)(Storage!(Object, string) storage, string[] args) {
    storage.args(args, T.init);
}
    
auto envs(T, R : Locator!())(R locator, string storageId = "parameters")
    if (!is(R : Storage!(Object, string)) && is(T == struct)) {
    import std.algorithm;
    
    auto storage = locator.locate!(Storage!(Object, string))(storageId);
    
    storage.envs!T;
    return locator;
}
    
auto args(T, R : Locator!())(R locator, string[] args, T initial, string storageId = "parameters")
    if (!is(R : Storage!(Object, string)) && is(T == struct)) {
    import std.algorithm;
    
    auto storage = locator.locate!(Storage!(Object, string))(storageId);
    
    storage.args(args, initial);
    return locator;
}
    
auto args(T, R : Locator!())(R locator, string[] args, string storageId = "parameters")
    if (!is(R : Storage!(Object, string))) {
    
    locator.args!T(args, T.init, storageId);
    return locator;
}

private {
    import aermicioi.util.traits;
    import std.meta;
    
    template publicFields(T) {
         alias publicFieldsImpl = chain!(
            partialPrefixed!(
                Filter,
                partialPrefixed!(
                    isField,
                    T
                )
            ),
            partialPrefixed!(
                Filter,
                partialSuffixed!(
                    partialPrefixed!(
                        isProtection,
                        T
                    ),
                    "public"
                )
            ),
            allMembers
        );
         
         alias publicFields = publicFieldsImpl!T;
    }
}