/**
This module is a container for a set of templates that are used across library and aren't bound to some specific module.
License:
	Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

Authors:
	Alexandru Ermicioi
**/
module aermicioi.aedi.util.traits.traits;
import std.traits;
import std.typetuple;
import std.algorithm;
import std.array;

public {

    enum bool isPublic(alias T) = __traits(getProtection, T) == "public";
    enum bool isPublic(alias T, string member) = getProtection!(T, member) == "public";

    template identifier(alias T) {
        alias identifier = Identity!(__traits(identifier, T));
    }

    template getMember(alias T, string member) {

        alias getMember = Identity!(__traits(getMember, T, member));
    }

    template getOverloads(alias T, string member) {

        alias getOverloads = AliasSeq!(__traits(getOverloads, T, member));
    }

    template typeOf(alias T) {
        static if (isValue!T) {
            alias typeOf = typeof(T);
        } else {
            alias typeOf = T;
        }
    }

    template getProtection(alias T, string member) {

        static if (__traits(compiles, __traits(getProtection, __traits(getMember, T, member)))) {
            enum auto getProtection = __traits(getProtection, __traits(getMember, T, member));
        } else {
            enum auto getProtection = "private";
        }
    }

    template getProtection(alias symbol) {
        static if (__traits(compiles, __traits(getProtection, symbol))) {
            enum auto getProtection = __traits(getProtection, symbol);
        } else {
            enum auto getProtection = "private";
        }
    }

    template isProtection(alias T, string member, string protection = "public") {
        enum bool isProtection = getProtection!(T, member) == protection;
    }

    template isProtection(T, string member, string protection = "public") {
        enum bool isProtection = getProtection!(T, member) == protection;
    }

    template isProtection(alias symbol, string protection) {
        enum bool isProtection = getProtection!symbol == protection;
    }

    template getMembersWithProtection(T, string member, string protection = "public") {
        import aermicioi.aedi.util.traits.partial : chain, eq;

        alias getMembersWithProtection = Filter!(
            chain!(
                eq!"public",
                getProtection
            ),
            __traits(getOverloads, T, member)
        );
    }

    template isField(T, string field) {

        auto isField() {
            import aermicioi.aedi.util.traits.partial : eq;
            static if (Filter!(eq!field, FieldNameTuple!T).length > 0) {
                return true;
            } else {
                return false;
            }
        }
    }

    template toType(T) {
        alias toType = T;
    }

    template toType(alias T) {
        static if (is(typeof(T))) {

            alias toType = typeof(T);
        } static if (is(T)) {

            alias toType = T;
        }
    }

    enum bool isDerived(alias T, alias Z) = is(T : Z);

    template isStaticFunction(alias method)  {
        enum bool isStaticFunction = __traits(isStaticFunction, method);
    }
}

private {
    alias Identity(alias A) = A;
}
