/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:
	
	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi.container.subscribable_container;

import aermicioi.aedi.container.container;
import aermicioi.aedi.storage.object_storage;
import aermicioi.aedi.storage.decorator;
import aermicioi.aedi.storage.alias_aware;
import aermicioi.aedi.storage.storage;
import aermicioi.aedi.factory.factory;
import aermicioi.aedi.exception.not_found_exception;
import aermicioi.util.traits;
import std.meta;
import std.traits;

import std.range.interfaces;
import std.typecons;

interface Subscribable(T) {
    
    public {
        
        Subscribable subscribe(
            T type,
            void delegate() subscriber
        );
    }
}

enum ContainerInstantiationEventType {
    pre,
    post,
}

template SubscribableContainer(T) {
    
    /**
    Set which the switchable container will decorate for T. By default
    Locator!() and Subscribable!ContainerInstantiationEventType is included.
    **/
    alias InheritanceSet = NoDuplicates!(Filter!(
        templateOr!(
            partialSuffixed!(
                isDerived,
                Storage!(ObjectFactory, string)
            ),
            partialSuffixed!(
                isDerived,
                AliasAware!string
            ),
            partialSuffixed!(
                isDerived,
                FactoryLocator!ObjectFactory
            )
        ),
        InterfacesTuple!T),
        Container,
        Subscribable!ContainerInstantiationEventType,
        MutableDecorator!T,
        Decorator!Container
    );
    
    class SubscribableContainer : InheritanceSet {
        private {
            void delegate()[][ContainerInstantiationEventType] subscribers;
            T decorated_;
        }
        
        public {
            
            this() {
                subscribers[ContainerInstantiationEventType.pre] = null;
                subscribers[ContainerInstantiationEventType.post] = null;
            }
            
            @property {
            	SubscribableContainer decorated(T container) @safe nothrow {
            		this.decorated_ = container;
            	
            		return this;
            	}
            	
            	T decorated() @safe nothrow {
            		return this.decorated_;
            	}
            }
            
            Object get(string key) {
                return this.decorated.get(key);
            }
            
            bool has(in string key) inout {
                return this.decorated_.has(key);
            }
            
            SubscribableContainer subscribe(
                ContainerInstantiationEventType event,
                void delegate() subscriber
            ) {
                this.subscribers[event] ~= subscriber;
                
                return this;
            }
            
            SubscribableContainer instantiate() {
                foreach (preProcessor; this.subscribers[ContainerInstantiationEventType.pre]) {
                    preProcessor();
                }
                
                this.decorated.instantiate();
                
                foreach (postProcessor; this.subscribers[ContainerInstantiationEventType.post]) {
                    postProcessor();
                }
                
                return this;
            }
            
            static if (is(T : Storage!(ObjectFactory, string))) {

                SubscribableContainer!T set(ObjectFactory element, string identity) {
                    decorated.set(element, identity);
                    
                    return this;
                }
                
                SubscribableContainer!T remove(string identity) {
                    decorated.remove(identity);
                    
                    return this;
                }
            }
            
            static if (is(T : AliasAware!string)) {
                SubscribableContainer!T link(string identity, string alias_) {
                    decorated.link(identity, alias_);
                    
                    return this;
                }
                
                SubscribableContainer!T unlink(string alias_) {
                    decorated.unlink(alias_);
                    
                    return this;
                }
                
                const(string) resolve(in string alias_) const {
                    return decorated_.resolve(alias_);
                }
            }
            
            static if (is(T : FactoryLocator!ObjectFactory)) {
                
                ObjectFactory getFactory(string identity) {
                    return this.decorated.getFactory(identity);
                }
                
                InputRange!(Tuple!(ObjectFactory, string)) getFactories() {
                    return this.decorated.getFactories();
                }
            }
        }
    }
}

