/**

License:
	Boost Software License - Version 1.0 - August 17th, 2003
    
    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:
    
    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

Authors:
	Alexandru Ermicioi
**/
module aermicioi.aedi.configurer.annotation;

import aermicioi.aedi.configurer.configurer;
import aermicioi.aedi.storage.locator;
import aermicioi.aedi.storage.storage;
import aermicioi.aedi.instantiator.instantiator;
import aermicioi.aedi.factory.factory;
import aermicioi.aedi.factory.genericfactory;
import aermicioi.util.traits;

import std.traits;
import std.meta;
import std.typecons;
import std.conv : to;

struct Component(T) {
    
    auto factory() {
        return new GenericFactoryImpl!T;
    }
}

struct Constructor(T...) {
    Tuple!T args;
    
    this(ref T args) {
        this.args = args;
    }
    
    auto factory(T)(GenericFactory!T factory) {
        factory.constructor(args);
        
        return factory;
    }
}

struct Method(T...) {
    Tuple!T args;
    
    this(ref T args) {
        this.args = args;
    }
    
    auto factory(T)(GenericFactory!T factory) {
        factory.method(args);
        
        return factory;
    }
}

private template canDeclareFactory(T) {
    enum bool canDeclareFactory = 
    hasMember!(T, "factory") && 
    isProtection!(T, "factory", "public") &&
    (MemberFunctionsTuple!(T, "factory").length == 1) &&
    (variadicFunctionStyle!(getMember!(T, "factory")) == Variadic.no) &&
    (arity!(getMember!(T, "factory")) == 0) &&
    is(ReturnType!(getMember!(T, "factory")) : GenericFactory!T, T);
}

private template canFactoryInstance(T) {
    // TODO
}

private template canConfigureInstance(T) {
    // TODO
}

private template isValue(Z, Z t) {
    enum bool isValue = true;
}

private template isValue(T) {
    enum bool isValue = false;
}

private template getProtection(T, string member) {
    static if (__traits(compiles, __traits(getProtection, __traits(getMember, T, member)))) {
        enum auto getProtection = __traits(getProtection, __traits(getMember, T, member));
    }
}

private template isProtection(T, string member, string protection = "public") {
    enum bool isProtection = getProtection!(T, member) == protection;
}

private template isReturnTypeEq(alias symbol, Type)
    if (isSomeFunction!symbol) {
    enum bool isReturnTypeEq = is(ReturnType!symbol : Type);
}

private template isNamedTemplate(alias T, string name) {
    enum bool isNamedTemplate = isTemplate!T && (identifier!T == name);
}

private template isEqByFQDN(alias first, alias second) {
    enum bool isEqByFQDN = fullyQualifiedName!first == fullyQualifiedName!second;
}

private template instantiatonToTemplate(alias T, alias Template = T) {
    static if (isTemplateInstantiationOf!(T, Template)) {
        alias instantiatonToTemplate = Template;
    } else static if (isTemplate!T) {
        alias instantiatonToTemplate = T;
    }
}

enum bool isTemplateInstantiationOf(T, alias Template) = is(T : Template!(Z), Z...);
enum bool isTemplateInstantiationOf(alias T, alias Template) = is(typeof(T) : Template!(Z), Z...);

private template identifierEq(alias T, string identity) {
    enum bool identifierEq = identifier!T == identity;
}

private template allUDAs(alias symbol) {
    alias allUDAs = AliasSeq!(__traits(getAttributes, symbol));
}

private template toValue(T) {
    enum auto toValue = T();
}

private template toValue(alias T) {
    alias toValue = T;
}

alias isType(T) = templateNot!(isValue!T);